/** Template base de keywords — nicho bienestar/capacitación/RRHH */
export const KEYWORD_TEMPLATE = [
  { categoria: "Capacitación", palabra: "capacitación" },
  { categoria: "Capacitación", palabra: "curso" },
  { categoria: "Capacitación", palabra: "taller" },
  { categoria: "Capacitación", palabra: "formación" },
  { categoria: "Capacitación", palabra: "e-learning" },
  { categoria: "Capacitación", palabra: "SENCE" },
  { categoria: "Capacitación", palabra: "OTEC" },
  { categoria: "Capacitación", palabra: "diplomado" },
  { categoria: "Capacitación", palabra: "workshop" },
  { categoria: "Capacitación", palabra: "inducción" },
  { categoria: "Capacitación", palabra: "congreso" },
  { categoria: "Capacitación", palabra: "charla" },
  { categoria: "Capacitación", palabra: "entrenamiento" },
  { categoria: "Bienestar", palabra: "bienestar" },
  { categoria: "Bienestar", palabra: "salud mental" },
  { categoria: "Bienestar", palabra: "mindfulness" },
  { categoria: "Bienestar", palabra: "burnout" },
  { categoria: "Bienestar", palabra: "estrés" },
  { categoria: "Bienestar", palabra: "autocuidado" },
  { categoria: "Bienestar", palabra: "psicoeducación" },
  { categoria: "Bienestar", palabra: "calidad de vida" },
  { categoria: "Bienestar", palabra: "programa wellness" },
  { categoria: "RRHH", palabra: "clima laboral" },
  { categoria: "RRHH", palabra: "desarrollo organizacional" },
  { categoria: "RRHH", palabra: "coaching" },
  { categoria: "RRHH", palabra: "liderazgo" },
  { categoria: "RRHH", palabra: "evaluación de desempeño" },
  { categoria: "RRHH", palabra: "selección de personal" },
  { categoria: "RRHH", palabra: "onboarding" },
  { categoria: "RRHH", palabra: "outplacement" },
  { categoria: "RRHH", palabra: "competencias" },
  { categoria: "Consultoría", palabra: "consultoría" },
  { categoria: "Consultoría", palabra: "asesoría" },
  { categoria: "Consultoría", palabra: "diagnóstico" },
  { categoria: "Consultoría", palabra: "facilitación" },
  { categoria: "Consultoría", palabra: "metodología" },
  { categoria: "Consultoría", palabra: "seminario" },
  { categoria: "Consultoría", palabra: "jornada" },
  { categoria: "RRHH", palabra: "mentoría" },
  { categoria: "RRHH", palabra: "mentorias" },
  { categoria: "Facilitación", palabra: "relatoría" },
  { categoria: "Facilitación", palabra: "relator" },
  { categoria: "Facilitación", palabra: "transcripción" },
  { categoria: "Facilitación", palabra: "monitoreo" },
  { categoria: "Facilitación", palabra: "facilitador" },
  { categoria: "Facilitación", palabra: "diseño instruccional" },
  { categoria: "Facilitación", palabra: "material didáctico" },
  { categoria: "Facilitación", palabra: "plataforma LMS" },
  { categoria: "Facilitación", palabra: "certificación" },
] as const;

/** Rubros UNSPSC frecuentes en nicho OTEC / capacitación / RRHH */
export const UNSPSC_OTEC_SEED = [
  { codigo: "86101600", nombre: "Servicios de capacitación en gestión" },
  { codigo: "86101500", nombre: "Servicios de capacitación comercial" },
  { codigo: "86101800", nombre: "Servicios de capacitación en recursos humanos" },
  { codigo: "86101700", nombre: "Servicios de capacitación en informática" },
  { codigo: "86101900", nombre: "Servicios de capacitación en ventas" },
  { codigo: "80101500", nombre: "Servicios de consultoría en gestión" },
  { codigo: "80101600", nombre: "Servicios de consultoría en recursos humanos" },
  { codigo: "80111500", nombre: "Servicios de consultoría en marketing" },
  { codigo: "80101700", nombre: "Servicios de consultoría en tecnología de información" },
  { codigo: "92101500", nombre: "Servicios de salud mental" },
  { codigo: "92101600", nombre: "Servicios de psicología" },
  { codigo: "92101700", nombre: "Servicios de terapia ocupacional" },
  { codigo: "80101800", nombre: "Servicios de consultoría en desarrollo organizacional" },
  { codigo: "86102000", nombre: "Servicios de capacitación en seguridad industrial" },
  { codigo: "86102100", nombre: "Servicios de capacitación en primeros auxilios" },
  { codigo: "80101900", nombre: "Servicios de consultoría en calidad" },
  { codigo: "92101800", nombre: "Servicios de medicina preventiva" },
  { codigo: "86102200", nombre: "Servicios de capacitación en idiomas" },
  { codigo: "80102000", nombre: "Servicios de consultoría en comunicaciones" },
  { codigo: "86102300", nombre: "Servicios de capacitación en habilidades blandas" },
] as const;

/**
 * Rubros registrados en Mercado Público — Consultora Capital Psicológico.
 * Códigos UNSPSC reales (familia) para matching con productos de cada CA/licitación.
 */
export const RUBROS_MERCADO_PUBLICO_TEMPLATE = [
  { codigo: "80101500", nombre: "Servicios de consultoría en gestión de empresas" },
  { codigo: "80101500", nombre: "Gestión de proyectos" },
  { codigo: "80101600", nombre: "Consultorías para el desarrollo de recursos humanos" },
  { codigo: "80111500", nombre: "Ventas y marketing" },
  { codigo: "80101500", nombre: "Servicios gerenciales y administrativos para el sector salud" },
  { codigo: "86101600", nombre: "Servicios de formación profesional científica" },
  { codigo: "86101500", nombre: "Servicios de formación profesional no científica" },
  { codigo: "86101800", nombre: "Desarrollo de recursos humanos" },
  { codigo: "86101700", nombre: "Aprendizaje a distancia" },
  { codigo: "86101500", nombre: "Educación de adultos" },
  { codigo: "80101500", nombre: "Consultoría" },
  { codigo: "80101900", nombre: "Planificación y Factibilidad" },
] as const;
